config/routes.rb
Rails.application.routes.draw do
  root to: "events#index"
  resources :events
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :users, only: [:index, :show]
  resources :charges, only: [:new, :create]
  post '/events/:id/participate', to: 'events#participate', as: 'participation'
  post '/events/:id/unparticipate', to: 'events#unparticipate', as: 'unparticipation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_and_belongs_to_many :attendees, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :created_events, class_name: 'Event', dependent: :destroy, foreign_key: 'creator_id'
  has_and_belongs_to_many :attended_events, class_name: 'Event'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Paiement de #{current_user.first_name} #{current_user.last_name}',
      :currency    => 'eur'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  #Take part in an event
  def participate
      @event = Event.find(params[:id])
      # Amount in cents
      @amount = @event.price

      if @amount.to_i > 0

          customer = Stripe::Customer.create(
            :email => params[:stripeEmail],
            :source  => params[:stripeToken]
          )

          charge = Stripe::Charge.create(
            :customer    => customer.id,
            :amount      => @amount,
            :description => 'Paiement de #{current_user.first_name} #{current_user.last_name}',
            :currency    => 'eur'
          )


        @event.attendees << current_user
        redirect_to @event

        return
      else

          @event.attendees << current_user
          redirect_to @event
          return

      end

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to @event

  end

  def unparticipate
    @event = Event.find(params[:id])
    @event.attendees.delete(current_user)
    render 'show'
  end


  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :date, :place, :price).merge(creator_id: current_user.id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Inscription à l'événement"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/events/_form.html.erb
<div class="row text-center">

  <div class="col-md-6 col-md-offset-3">

<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "erreur") %> a empêché la mise à jour de cet événement :</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <label>Nom</label><br>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="field">
      <label>Description</label><br>
      <%= form.text_area :description, class: 'form-control' %>
    </div>

    <div class="field">
      <label>Date</label><br>
      <%= form.date_field :date, class: 'form-control' %>
    </div>

    <div class="field">
      <label>Lieu</label><br>
      <%= form.text_field :place, class: 'form-control' %>
    </div>

    <div class="field">
      <label>Prix (en centimes d'€)</label><br>
      <%= form.number_field :price, class: 'form-control', :min => '0', :step => '1' %>
    </div>

    <div class="actions">
      <%= form.submit 'Go !' %>
    </div>

  </div>

</div>
<% end %>

app/views/events/edit.html.erb
<h1>Editer l'événement</h1>

<% if @event.creator == current_user %>

  <%= render 'form', event: @event %>

  <%= link_to 'Afficher l\'événement', @event %> |
  <%= link_to 'Retour', events_path %>

<% else %>

<p class="alert alert-danger">Etes-vous le créateur de cet événement ? Si oui, veuillez vous connecter.</p>

<% end %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Evénements</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Description</th>
      <th>Date</th>
      <th>Lieu</th>
      <th>Prix</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.date %></td>
        <td><%= event.place %></td>
        <td><%= event.price %></td>
        <td><%= link_to 'Plus d\'infos', event %></td>

        <% if event.creator == current_user %>
        <td><%= link_to 'Editer', edit_event_path(event) %></td>
        <td><%= link_to 'Supprimer', event, method: :delete, data: { confirm: 'Etes-vous sûr ?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
    <center><%= button_to 'Créer un nouvel événement', new_event_path, class: "btn btn-primary", method: :get %></center>
</div>
</div>
</div>
<% end %>

app/views/events/new.html.erb
<h1>Nouvel Evénement</h1>

<% if user_signed_in? %>

  <%= render 'form', event: @event %>

  <div class="text-center">
  <%= link_to 'Retour', events_path %>
  </div>

<% else %>

  <p class="alert alert-danger">Veuillez vous connecter ou créer un compte !</p>

<% end %>

app/views/events/show.html.erb
<div class="row text-center">

  <div class="col-md-12">
    <p id="notice"><%= notice %></p>

    <h1><%= @event.name %></h1>
    <table class="table table-striped">
      <tr>
        <th>Description</th>
        <th>Date</th>
        <th>Lieu</th>
        <th>Prix</th>
      </tr>

      <tr>
        <td><%= @event.description %></td>
        <td><%= @event.date %></td>
        <td><%= @event.place %></td>
        <td><%= @event.price %></td>

      </tr>

    </table>

    <h2>Liste des participants</h2>
    <table class="table table-striped">
      <tr>
        <th>Prénom</th>
        <th>Nom</th>
      </tr>

    <% @event.attendees.each do |attendee| %>

      <tr>
        <td><%= attendee.first_name %></td>
        <td><%= attendee.last_name %></td>
      </tr>

    <% end %>

    </table>

    <% if @event.attendees.include?(current_user) %>
    <%= button_to 'Je me désinscris', action: "unparticipate", class: "btn btn-danger" %>

    <% elsif !@event.attendees.include?(current_user) && user_signed_in? && @event.price.to_i == 0 %>
    <%= button_to 'Je participe !', action: "participate", class: "btn btn-primary" %>

    <% elsif !@event.attendees.include?(current_user) && user_signed_in? && @event.price.to_i > 0 %>

          <%= form_tag participation_path do %>
          <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
          <label class="amount">
          <span>Amount: <%= @event.price.to_f / 100 %>€</span>
          </label>
          </article>

          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="Paiement de l'événement"
                data-amount="<%= @event.price %>"
                data-currency="eur"
                data-locale="auto"></script>
          <% end %>


    <% else %>

    <% end %>

    <% if @event.creator == current_user %>
      <%= link_to 'Editer', edit_event_path(@event) %> |
      <% end %>

      <%= link_to 'Retour', events_path %>


  </div>

</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-inverse">
  <div class="container">
  <nav>
    <%= link_to "Larry's Events", root_path, class: "navbar-brand", id: "logo" %>

    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item"><%= link_to 'Evénements', events_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Membres', users_path, class: 'nav-link' %></li>

      <% if user_signed_in? %>
      <li class="nav-item"><%= link_to 'Créer un événement', new_event_path, class: 'nav-link' %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Bienvenue, <%= current_user.first_name %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Mon Profil", user_path(current_user) %></li>
          <li class="divider"></li>
          <li>  <%= link_to('Déconnexion', destroy_user_session_path, method: :delete) %></li>
        </ul>
      </li>

      <% else %>
      <li class="nav-item"><%= link_to 'Se connecter', new_user_session_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Créer un compte', new_user_registration_path, class: 'nav-link' %></li>

      <% end %>

    </ul>

  </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Tous nos membres</h1>

<table class="table table-striped">
  <tr>
    <th>Prénom</th>
    <th>Nom</th>
    <th>Email</th>
  </tr>

<% @users.each do |user| %>
  <tr>
  <td><%= user.first_name %></td>
  <td><%= user.last_name %></td>
  <td><%= user.email %></td>
  </tr>

<% end %>

</table>

app/views/users/show.html.erb
<% if user_signed_in? %>

  <h1><%= @user.first_name + " " + @user.last_name %> - Mon Profil</h1>

  <div class="container-fluid">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">

    </div>

  </div>

    <div class="row">

      <div class="col-md-6">
        <h3 style="text-align:left">Je suis l'organisateur de ...</h3>
        <ul>

          <% @user.created_events.each do |event| %>
          <li><%= event.name %>, le <%= event.date %> à <%= event.place %></li>
          <% end %>

        </ul>
      </div>

      <div class="col-md-6">
        <h3 style="text-align:left">Je participe à ...</h3>
        <ul>

          <% @user.attended_events.each do |event| %>
          <li><%= event.name %>, le <%= event.date %> à <%= event.place %></li>
          <% end %>

        </ul>
      </div>



    </div>

  </div>

<% else %>

<p class="alert alert-danger">Veuillez vous connecter pour visualiser votre profil !</p>

<% end %>